### PR TITLE
Detect code blocks and markdown links

### PR DESCRIPTION
**Pull request by Peter-Schorn**
These lines should not be wrapped. See the new test for an example.

### CODE REVIEW

**Comment by SteveBarnegren** [comment]
Hi Peter 👋

Thanks for this. I've had a look through the code and it all looks great.

Thanks also for tidying up some of the control flow - the switch statements read much better than the if / else chains.

The test is very much appreciated also!

I'm going to merge this in now, and hopefully I'll be able to submit a new version to the store soon 👍

**Comment by Peter-Schorn** [comment]
I prefer to wrap the lines in my projects based on the absolute length of each line, including any leading indentation. I found a way to do this, but I wasn't sure how to create a setting that allows a user to turn this on/off.

If this feature was enabled, then you would change
https://github.com/SteveBarnegren/XcodeCommentWrapper/blob/3a9366aa152e51068374bfb411b17cf84502ef83/CommentWrapperExt/CommentWrapper.swift#L22
to 
```
let wrappedString = wrap(items: items, lineLength: lineLength - prefix.count)
```

Is this something you would be willing to add? I would be very helpful to me. You could turn it off by default, of course.

**Comment by SteveBarnegren** [comment]
Hi Peter, just letting you know that I've uploaded version 1.1 to the App Store with your additions. Thank you!

I've never thought of that actually. I wonder if it's something that others would find useful or not.

I'm not against adding it at all. It's a developer tool, so I think it's an audience that appreciates having options for these types of things. The only challenge is to have some sort of communication between the host app and the extension in order to have a place to adjust the settings.

I'm sure that's possible, it just takes some time to figure it out!

I don't have the time to look in to it myself at the moment, but if you want to give it a go then I'd consider merging it in to the project.

**Comment by Peter-Schorn** [comment]
I'll consider trying to implement it myself. The challenging part for me would be the UI. I have little experience with AppKit. We can just store the setting in `UserDefaults`.

**Pull request merged**
